### ISSUE TITLE
Not working Postgre 9.5

### ISSUE THREAD

**Issue by alexk984** [nanson/yii2-postgis#1]
```
"name":"Database Exception",
"message":"SQLSTATE[42601]: Syntax error: 7 ERROR: syntax error at or near "point" LINE 1: SELECT ST_asGeoJson('(41.63901, "72"."957299)')" AS "point" ^ The SQL being executed was: SELECT ST_asGeoJson('(41.63901, "72"."957299)')" AS "point"",
"code":42601,
"type":"yii\db\Exception",
"file":"/var/www/immulet/vendor/yiisoft/yii2/db/Schema.php",
"line":633,
"stack-trace":[
"#0 /var/www/immulet/vendor/yiisoft/yii2/db/Command.php(915): yii\db\Schema->convertException(Object(PDOException), 'SELECT ST_asGeo...')",
"#1 /var/www/immulet/vendor/yiisoft/yii2/db/Command.php(376): yii\db\Command->queryInternal('fetch', NULL)",
"#2 /var/www/immulet/vendor/nanson/yii2-postgis/behaviors/GeometryBehavior.php(209): yii\db\Command->queryOne()",
"#3 /var/www/immulet/vendor/nanson/yii2-postgis/behaviors/GeometryBehavior.php(140): nanson\postgis\behaviors\GeometryBehavior->postgisToGeoJson()",
"#4 [internal function]: nanson\postgis\behaviors\GeometryBehavior->afterFind(Object(yii\base\Event))",
"#5 /var/www/immulet/vendor/yiisoft/yii2/base/Component.php(541): call_user_func(Array, Object(yii\base\Event))",
"#6 /var/www/immulet/vendor/yiisoft/yii2/db/BaseActiveRecord.php(864): yii\base\Component->trigger('afterFind')",
"#7 /var/www/immulet/vendor/yiisoft/yii2/db/ActiveQuery.php(224): yii\db\BaseActiveRecord->afterFind()",
"#8 /var/www/immulet/vendor/yiisoft/yii2/db/Query.php(211): yii\db\ActiveQuery->populate(Array)",
```

**Comment by thedenische** [comment]
Как я понимаю, ошибка возникает при чтении модели из БД. В каком виде в БД хранится атрибут модели, к которому подключено поведение?
И еще было бы неплохо увидеть само объявление поведения в модели.

**Comment by alexk984** [comment]
Поле в таблице: `"point" point NOT NULL,`
Подключение поведения:

```
public function behaviors()
    {
        return [
            [
                'class' => GeometryBehavior::className(),
                'type' => GeometryBehavior::GEOMETRY_POINT,
                'attribute' => 'point',
            ],
        ];
    }
```

**Comment by thedenische** [comment]
Метод `GeometryBehavior->postgisToGeoJson()` вызывается afterFind, для преобразование бинарного формата postgis в geoJson. Т.е. там должен выходить запрос вида:

``` sql
SELECT ST_asGeoJson('0101000020E610000046000088D1CF424028BAB36FA7E04B40') AS "point"
```

А `PostgisQueryTrait` используется?

**Comment by alexk984** [comment]
```
$res = $query->select("ST_asGeoJson('" . $this->owner->$attribute . "') as $attribute")->createCommand()->queryOne();
```

В это строчке берется значение атрибуты point, у меня там (41.63901,72.957299). 
`PostgisQueryTrait` - не знаю, уже удалил экстеншен

**Comment by thedenische** [comment]
>  у меня там (41.63901,72.957299)

по идее там должны быть данные в формате postgis, что-то в таком виде
`0101000020E610000046000088D1CF424028BAB36FA7E04B40`
Расширение postgis для postgres вообще установлено?

**Comment by alexk984** [comment]
Нет

**Comment by thedenische** [comment]
ну так это расширение именно для работы с [postgis](http://postgis.net/)
